### PR TITLE
Various fixes and updates

### PR DESCRIPTION
**Pull request by OgreTransporter**
**CMake fixes for MSVC**
Compiler flags like `-Wl,-Map,${PROJECT_NAME}.map` are not working for MSVC.

**Remove static plugin linking**
It is not necessary to link plugins in Qt 5.10+

**Fix 3345a6f which removed the features of pull request #13**
Commit 3345a6f has removed all features of pull request #13 including the features from issues 11 and 12.

**Fix translations**
Missing renaming from wpmcpp to npackdg in main.cpp for loading translations.

**Remove close buttons from non-closable tabs**
The tabs _Packages_ and _Jobs_ cannot be closed. Therefore the close button is removed.

### CODE REVIEW

**Comment by tim-lebedkov** [comment]
Do you plan to fix the automated build?

**Comment by OgreTransporter** [comment]
Yes, my mistake. I corrected the spelling mistake.

Edit: AppVeyor failed again, but it is not a coding error "Authorization failed."

**Comment by OgreTransporter** [comment]
Ok now?

**Comment by tim-lebedkov** [comment]
Thanks. I will look into this when 1.24 is out

**Pull request merged**
