### PR TITLE
Allow only one instance

### PR DESCRIPTION
**Pull request by OgreTransporter**
Solution for https://github.com/tim-lebedkov/npackd/issues/456

### CODE REVIEW

**Comment by tim-lebedkov** [comment]
Please, give me a good reason to merge this! 

I really do not see any sense in this change at the moment. Why would somebody need this?

For the future, please talk to me before you start changing something. Chances are I refuse to merge it and you would waste your time!

**Comment by OgreTransporter** [comment]
I'm sorry, but you marked that issue as "enhancement". If you don't like that feature, please close the ticket and decline it. Of course, I try to fix issues - that's the idea of the ticketing system. I will not fix or improve anything, if I have to ask you for each ticket first. Also, this patch is not a Problem. The function CreateMutex is available since Windows XP.

I want to change three more things, if you don't like them, I make them in a separate branch. I would like to add a flag to the build to set whether or not the program is looking for the known software. With a second flag I want to set whether the program has to work with admin privileges or whether the local user is sufficient. Instead of build flags I can also add options to npacked. I want to make a repository of ZIP archives available to my colleagues who all have no admin privileges. The programs are all portable and they run without admin rights. NET, Java etc. are managed by our administrator, so I don't need to search and display them. The last change is to set the program options via group policy on the network. The administrator can specify the repository and npacked settings, and users can then install only shared packages.

**Comment by tim-lebedkov** [comment]
This is also partly my fault. "Enhancement" tag only means that it is not a bug. Only issues with a version tag will be definitely implemented. I will talk to the guy who filed the issue. Maybe he can convince me :-)

All 3 of your suggestions seem reasonable. Could you please file 3 issues in the "npackd-cpp" project. I'd like to ask a couple of questions re. each one.

**Comment by OgreTransporter** [comment]
Ok, two new issues:

1. https://github.com/tim-lebedkov/npackd-cpp/issues/11
2. https://github.com/tim-lebedkov/npackd-cpp/issues/12

**Pull request closed without merging**
